### ISSUE TITLE
Can I have your email address?

### ISSUE THREAD

**Issue by seongminee** [MattWeiler/ProductKeyGenerator#1]
hello.
I'd like to ask you something. Can I have your email address? My email is ysm1022@gmail.com.

**Comment by MattWeiler** [comment]
Hi @comjangee ,

Matt I ask why you would like my email address?
I get so much spam these days, I'm just curious.

**Comment by comjangee** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you for your reply. I found your ProductKeyGeneration Git repository during Google search. So I wanted to use your ProductKeyGeneration Source in my web project, But I couldn't find the license policy.Can you explain to me the licensing policy for ProductKeyGeneration?--------- 원본 메일 ---------

  
    보낸사람: Matthew Weiler ***@***.***>
    받는사람: MattWeiler/ProductKeyGenerator ***@***.***>
      참조: comjangee ***@***.***>,Mention ***@***.***>
    날짜: 24.03.05 02:41 GMT +0900
    
    제목: Re: [MattWeiler/ProductKeyGenerator] Can I have your email address? (Issue #1)
    
    
  
  
    
Hi @comjangee ,
Matt I ask why you would like my email address?
I get so much spam these days, I'm just curious.

**Comment by seongminee** [comment]
Hi. @MattWeiler 

Thank you for your reply.
I found your ProductKeyGeneration Git repository during Google search.
I wanna use your ProductKeyGeneration Source in my web project,
But I couldn't find the license policy.
Can you explain to me the licensing policy for ProductKeyGeneration?

**Comment by MattWeiler** [comment]
Hi @comjangee 

Sorry, I didn't see your response until now.
We just welcomed our 2nd child into our lives, and life has gotten pretty busy again :)

I don't have any objection to my code being used, but since I simply ported it from an online example many years ago, I've reached out to the original author of the Delphi example to see if he has a license policy in place.

If he replies that he's ok with it, then I'll update my project with an MIT license making it a short and simple permissive license with conditions only requiring preservation of copyright and license notices.

**Comment by MattWeiler** [comment]
@comjangee 

Looking at the source blog post, I don't think there is any issue with me assigning a MIT license to my code since that blog post was clearly posted to help people implement such a product-key system in their own system.

As such, I've added a MIT license to my project, so have fun :)

**Comment by seongminee** [comment]
Thank you so much for your reply. 
First of all, congratulations on the birth of your second child. 
I also had my second child a year ago. 
So I know how hard and busy you are and how happy you are. 
I pray that your family and your child will always be blessed.

**Comment by MattWeiler** [comment]
> Thank you so much for your reply. First of all, congratulations on the birth of your second child. I also had my second child a year ago. So I know how hard and busy you are and how happy you are. I pray that your family and your child will always be blessed.

Thank you @comjangee , we're very excited. Most importantly is that our first daughter loves her new sister. 

I hope the keygen code is useful for you :)
It was a fun thing to write.
